openapi: 3.0.0
info:
  title: 中大图书 API
  description: 中大图书 API 的Swaager界面
  version: 1.0.0

servers:
  - url: http://api.example.com/v1
    description: Optional server description, e.g. Main (production) server
  - url: http://staging-api.example.com
    description: Optional server description, e.g. Internal staging server for testing

tags:
- name: "auth"
  description: "处理微信小程序登录相关代码"
  externalDocs:
    description: "更多"
    url: "https://developers.weixin.qq.com/miniprogram/dev/api/"
- name: "user"
  description: "处理用户信息逻辑"
- name: "book"
  description: "处理订单信息逻辑"

paths:
  /auth/getSession:
    post:
      tags:
      - "auth"
      summary: "用微信code换取小程序session"
      description: ""
      operationId: "getSession"
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                wxcode:
                  type: string
      responses:
        '200':
          description: "成功登陆返回session"
          content:
            application/json:
              schema:
                type: object
                properties:
                  session: 
                    type: string
        '403':
          description: "非法登录"
          
  /user:
    post:
      tags:
      - "user"
      summary: "创建用户信息"
      description: ""
      operationId: "createUser"
      parameters:
        - in: cookie
          name: session
          description: 有效session
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '201':
          description: "用户创建成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
  /user/{userid}:
    get:
      tags:
      - "user"
      summary: "根据用户ID获得用户信息"
      description: ""
      operationId: "getUserById"
      parameters:
      - name: "userid"
        in: "path"
        description: "用户id "
        required: true
        schema:
            type: integer
      responses:
        '200':
          description: "获得用户信息成功"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/User"
        '400':
          description: "用户ID无效"
        '404':
          description: "用户未找到"
    put:
      tags:
      - "user"
      summary: "更新用户信息"
      description: ""
      operationId: "updateUser"
      parameters:
        - in: cookie
          name: session
          description: 有效session
          schema:
            type: string
        - name: "userid"
          in: "path"
          description: "用户id "
          required: true
          schema:
              type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '400':
          description: "Invalid user supplied"
        '404':
          description: "User not found"
    delete:
      tags:
      - "user"
      summary: "删除用户"
      description: ""
      operationId: "deleteUser"
      parameters:
        - name: "userid"
          in: "path"
          description: "用户id "
          required: true
          schema:
              type: integer
        - in: cookie
          name: session
          description: 有效session
          schema:
            type: string
      responses:
        '400':
          description: "Invalid username supplied"
        '404':
          description: "User not found"
  /book/{bookid}:
    get:
      tags:
      - "book"
      summary: 获取订单信息
      operationId: getBook
      description: ""
      parameters:
      - in: path
        description: 订单id
        name: bookid
        required: true
        schema:
          type: integer
      responses:
        '200':
          description: 订单详细信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '401':
          description: unauthorized
        '404':
          description: lend book not found
    post:
      tags:
      - "book"
      summary: 添加订单信息
      operationId: addBook
      description: ""
      parameters:
      - in: path
        description: lend book id
        name: bookid
        required: true
        schema:
          type: integer
      - in: cookie
        name: session
        description: 有效session
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: 订单详细信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '401':
          description: unauthorized
        '404':
          description: invalid input, object invalid
        '409':
          description: duplicate lend book
    put:
      tags:
      - "book"
      summary: 更新订单信息
      operationId: updateLend
      description: ""
      parameters:
      - in: path
        description: lend book id
        name: bookid
        required: true
        schema:
          type: integer
      - in: cookie
        name: session
        description: 有效session
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/User"
      responses:
        '200':
          description: 订单详细信息
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Book'
        '401':
          description: unauthorized
        '404':
          description: invalid input, object invalid
        '409':
          description: duplicate lend book
    delete:
      tags:
      - "book"
      summary: 删除订单信息
      operationId: deleteLend
      description: ""
      parameters:
      - in: path
        description: lend book id
        name: bookid
        required: true
        schema:
          type: integer
      - in: cookie
        name: session
        description: 有效session
        schema:
          type: string
      responses:
        '200':
          description: return success message
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: success
        401:
          description: unauthorized
        404:
          description: invalid input, object invalid
  
components:
  schemas:
    User:
      type: "object"
      properties:
        id:
          type: "integer"
          format: "int64"
        name:
          type: "string"
        gender:
          type: "integer"
          format: "int32"
          description: "0为女，1为男"
        description:
          type: "string"
        email:
          type: "string"
        wechat:
          type: "string"
      required:
        - name
        - gender
    Book:
      type: object
      properties:
        id:
          type: "integer"
          format: "int64"
          example: 1
        name:
          type: "string"
          example: "1984"
        isbn:
          type: "string"
          example: "123"
        description:
          type: "string"
          example: "书的简介"
        image:
          type: "string"
          example: "localhost/images/a.jpg"
        start:
          type: "object"
        end:
          type: "object"
        enable:
          type: "integer"
        booktype:
          type: "integer"
          description: "0表示借出，1表示借入"
        userId:
          type: "integer"
          format: "int64"
          example: 1
        
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  
                  